name = "hunydev-works"
main = "server/worker.ts"
compatibility_date = "2025-02-15"
workers_dev = true

[assets]
directory = "dist/client"
# By default this binds to `env.ASSETS` in the Worker
binding = "ASSETS"

[[r2_buckets]]
binding = "R2"         # accessible as env.R2 in the worker
bucket_name = "hunydev" # your R2 bucket name

[vars]
# Example for future server-side keys
PB_LOGIN_EMAIL = "api@huny.dev"
NOTION_BOOKMARK_ID = "8fd541f1-6b68-4358-aa40-8b472ecad670"
NOTION_API_VERSION = "2025-09-03"
