name: Deploy

on:
  schedule:
    - cron: '0 1 * * *' # 매일 10시 KST (01:00 UTC)
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler deploy

      - name: Send ntfy alert on success
        if: success()
        env:
          NTFY_ACCESS_TOKEN: ${{ secrets.NTFY_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $NTFY_ACCESS_TOKEN" \
            -H 'Title: Deploy Success' \
            -H 'Tags: white_check_mark,rocket' \
            -d "huny.dev 배포가 완료되었습니다. 완료 시각(UTC): $(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            https://ntfy.sh/hunydev

      - name: Send ntfy alert on failure
        if: failure()
        env:
          NTFY_ACCESS_TOKEN: ${{ secrets.NTFY_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $NTFY_ACCESS_TOKEN" \
            -H 'Title: Deploy Failure' \
            -H 'Tags: warning,x' \
            -d "huny.dev 배포가 실패했습니다. 실패 시각(UTC): $(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            https://ntfy.sh/hunydev
